### ISSUE TITLE
Can't find the database file, no matter what

### ISSUE THREAD

**Issue by ChanceNCounter** [pbkhrv/ulauncher-keepassxc#11]
I've tried moving my kdbx, I've tried renaming it, I've tried creating a symlink with the default name. No matter what I do, I get "cannot find the database file."

We could troubleshoot this, but it seems more sensible to suggest a file chooser.

**Comment by pbkhrv** [comment]
I'm sorry that it's not working for you. I did just fix a bug in the code where file paths starting with `~` weren't handled properly when set from the Preferences window. If you could do me a huge favor and re-install this extension and try again, I'd really appreciate it.

As for a file selector - that would be amazing, however the Preference window is something that Ulauncher itself controls, and there is no way that I can see to tell it to use a file selector for a particular config value.

**Comment by ChanceNCounter** [comment]
Yep! That seems to have done it. I suppose I picked that wondrous moment to try the extension between when you fixed it and when the fix took hold. Thank you!

Regarding the other thing, fair enough. I imagine that you could kludge it with a pygame-based toolkit, but that would be a LOT of bloat for I suppose relatively little gain.

Thanks again!

**Comment by pbkhrv** [comment]
Awesome, thanks for your help!
